baseURL = "https://Biotin-2small.github.io/"
locale = "zh-cn"
title = "关注biotin喵，关注biotin谢谢喵"
theme = "PaperMod"

[params]
  author = "biotin"
  description = "分享技术、生活与思考"
  darkMode = "auto"
  search = true
[[menu.main]]
  name = "首页"
  url = "/"
  weight = 10
[[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 20
[[menu.main]]
  name = "搜索"
  url = "/search/"
  weight = 30