baseURL = "https://Biotin-2small.github.io/"
locale = "zh-cn"
title = "测试用个人网站"
theme = "PaperMod"

[params]
  author = "biotin"
  description = "分享技术、生活与思考"

  
[params.search]
  enable = true
params:
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

  socialIcons: # optional
    - name: "<platform>"
      url: "<link>"
    - name: "<platform 2>"
      url: "<link2>"